### ISSUE TITLE
UnmarshalKey would panic if a map is um marshalled into a slice

### ISSUE THREAD

**Issue by fefe982** [spf13/viper#1011]
With viper v1.7.1, the following program would panic:
```
package main

import (
	"bytes"
	"fmt"

	"github.com/spf13/viper"
)

func main() {
	viper.SetConfigType("yaml")
	var yamlExample = []byte(`
map:
  a: a
  b: b
`)
	viper.ReadConfig(bytes.NewBuffer(yamlExample))
	slice := make([]string, 0)
	viper.UnmarshalKey("map", &slice)
	fmt.Printf("%v\n", viper.Get("map"))
}
```

The panic is in map structure:
```
panic: reflect: call of reflect.Value.Index on map Value

goroutine 1 [running]:
reflect.Value.Index(0x6476c0, 0xc0000e3740, 0x15, 0x0, 0x6396a0, 0x5d81be, 0x6476c0)
        /usr/local/go/src/reflect/value.go:978 +0x1ba
github.com/mitchellh/mapstructure.(*Decoder).decodeSlice(0xc000010080, 0x0, 0x0, 0x6476c0, 0xc0000e3740, 0x6396a0, 0xc00000e700, 0x197, 0x6476c0, 0xc0000e3740)
        /go/pkg/mod/github.com/mitchellh/mapstructure@v1.1.2/mapstructure.go:856 +0x54a
github.com/mitchellh/mapstructure.(*Decoder).decode(0xc000010080, 0x0, 0x0, 0x6476c0, 0xc0000e3740, 0x6396a0, 0xc00000e700, 0x197, 0xc00000e700, 0x197)
        /go/pkg/mod/github.com/mitchellh/mapstructure@v1.1.2/mapstructure.go:294 +0x7e5
github.com/mitchellh/mapstructure.(*Decoder).Decode(0xc000010080, 0x6476c0, 0xc0000e3740, 0x0, 0xc00000e760)
        /go/pkg/mod/github.com/mitchellh/mapstructure@v1.1.2/mapstructure.go:222 +0xf0
github.com/spf13/viper.decode(0x6476c0, 0xc0000e3740, 0xc0000cc640, 0x0, 0x0)
        /go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:935 +0x70
github.com/spf13/viper.(*Viper).UnmarshalKey(0xc0000fe6c0, 0x68414d, 0x3, 0x6313a0, 0xc00000e700, 0x0, 0x0, 0x0, 0xc0001c1f78, 0x407c85)
        /go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:899 +0xb7
github.com/spf13/viper.UnmarshalKey(...)
        /go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:896
main.main()
        /go/src/*****/main.go:19 +0x1ce
```

I would expect an error to be returned here, instead of panic.

**Comment by fefe982** [comment]
Tested mapstructure with:

```
import (
	"fmt"

	"github.com/mitchellh/mapstructure"
)

func main() {
	slice := make([]string, 0)
	err := mapstructure.Decode(map[string]string{"a": "a", "b": "b"}, &slice)
	fmt.Printf("%v, %v\n", slice, err)
}
```

The v1.1.2 of mapstructure (which is used by viper) would panic.
The v1.3.3 (most recent version now) of mapstructure would not panic, instead it prints:
```
[], '': source data must be an array or slice, got map
```

I don't know on which version this is fixed.

**Comment by fefe982** [comment]
Just found that mapstructure has already been upgraded to v1.3.3 on master.

I think I'll just have to wait for the next release.
