### ISSUE TITLE
Build with error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Virgil-N** [spf13/viper#1116]
**Expected behavior (what you expected to happen)**: Build with no errors.

**Actual behavior (what actually happened)**:
Error:
Build with error: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa8eda9]

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa8eda9]

goroutine 1 [running, locked to thread]:
log.(*Logger).Panicf(0xc000095360, 0x2348ac5, 0x3, 0xc00021f990, 0x1, 0x1)
        C:/mySoftware/go/src/log/log.go:228 +0xcc
github.com/Virgil-N/fyne_app/client/views/mainlayout.init.0.func1()
        C:/private_workspace/fyne_app/client/views/mainlayout/index.go:89 +0x185
panic(0x22924c0, 0x21d1020)
        C:/mySoftware/go/src/runtime/panic.go:969 +0x1c7
github.com/spf13/viper.(*Viper).find(0x0, 0xc0002d6df0, 0x3, 0x1, 0xc00021fd18, 0x58fc9f)
        C:/Users/zn/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:1027 +0x49
github.com/spf13/viper.(*Viper).Get(0x0, 0x2348b88, 0x3, 0x0, 0xc0002c9650)
        C:/Users/zn/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:728 +0x88
github.com/spf13/viper.(*Viper).GetStringMap(0x0, 0x2348b88, 0x3, 0xc0002c9630)
        C:/Users/zn/go/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:871 +0x46
github.com/Virgil-N/fyne_app/client/views/mainlayout.init.0()
        C:/private_workspace/fyne_app/client/views/mainlayout/index.go:103 +0x8e

**Environment**: windows 10 / MAC M1
- Viper version: 1.7.1

**Comment by sagikazarmark** [comment]
@Virgil-N please provide a code example that reproduces the issue. Thanks!

**Comment by passakornC** [comment]
I found the same issue, the first time I initialize `v := &viper.Viper{}` but after I change to `v := viper.New()` the problem is solved.

**Comment by sagikazarmark** [comment]
Closing due to lack of activity
