### ISSUE TITLE
viper.Sub() fails when the subtree is an array

### ISSUE THREAD

**Issue by satyenr** [spf13/viper#171]
### Example

``` go

package main

import (
  "bytes"
  "github.com/davecgh/go-spew/spew"
  "github.com/spf13/viper"
  "fmt"
)

var yamlData = []byte(`
baz: &BAZ
  name: baz
  value: "Hello YAML"
  type: string

bar: &BAR
  name: bar
  value: 10
  type: number

foo:
  name: foo
  array:
  - *BAR
  - *BAZ
  dict:
    baz: *BAR
    bar: *BAZ

  debug: true
`)



func main() {
  viper.SetConfigType("yaml")
  viper.ReadConfig(bytes.NewBuffer(yamlData))

  fmt.Println("GET foo.array")
  spew.Dump(viper.Get("foo.array"))
  fmt.Println("SUB foo.array")
  spew.Dump(viper.Sub("foo.array"))
  fmt.Println("GET foo.dict")
  spew.Dump(viper.Get("foo.dict"))
  fmt.Println("SUB foo.dict")
  spew.Dump(viper.Sub("foo.dict")) 
}

```
### Output

```
GET foo.name
(string) (len=3) "foo"
GET foo.array
([]interface {}) (len=2 cap=2) {
 (map[interface {}]interface {}) (len=3) {
  (string) (len=4) "type": (string) (len=6) "number",
  (string) (len=4) "name": (string) (len=3) "bar",
  (string) (len=5) "value": (int) 10
 },
 (map[interface {}]interface {}) (len=3) {
  (string) (len=4) "name": (string) (len=3) "baz",
  (string) (len=5) "value": (string) (len=10) "Hello YAML",
  (string) (len=4) "type": (string) (len=6) "string"
 }
}
SUB foo.array
(*viper.Viper)(<nil>)
GET foo.dict
(map[string]interface {}) (len=2) {
 (string) (len=3) "bar": (map[interface {}]interface {}) (len=3) {
  (string) (len=4) "name": (string) (len=3) "baz",
  (string) (len=5) "value": (string) (len=10) "Hello YAML",
  (string) (len=4) "type": (string) (len=6) "string"
 },
 (string) (len=3) "baz": (map[interface {}]interface {}) (len=3) {
  (string) (len=4) "name": (string) (len=3) "bar",
  (string) (len=5) "value": (int) 10,
  (string) (len=4) "type": (string) (len=6) "number"
 }
}
SUB foo.dict
(*viper.Viper)(0xc8200aa540)({
 keyDelim: (string) (len=1) ".",
 configPaths: ([]string) <nil>,
 remoteProviders: ([]*viper.defaultRemoteProvider) <nil>,
 configName: (string) (len=6) "config",
 configFile: (string) "",
 configType: (string) "",
 envPrefix: (string) "",
 automaticEnvApplied: (bool) false,
 envKeyReplacer: (*strings.Replacer)(<nil>),
 config: (map[string]interface {}) (len=2) {
  (string) (len=3) "bar": (map[interface {}]interface {}) (len=3) {
   (string) (len=4) "name": (string) (len=3) "baz",
   (string) (len=5) "value": (string) (len=10) "Hello YAML",
   (string) (len=4) "type": (string) (len=6) "string"
  },
  (string) (len=3) "baz": (map[interface {}]interface {}) (len=3) {
   (string) (len=4) "type": (string) (len=6) "number",
   (string) (len=4) "name": (string) (len=3) "bar",
   (string) (len=5) "value": (int) 10
  }
 },
 override: (map[string]interface {}) {
 },
 defaults: (map[string]interface {}) {
 },
 kvstore: (map[string]interface {}) {
 },
 pflags: (map[string]viper.FlagValue) {
 },
 env: (map[string]string) {
 },
 aliases: (map[string]string) {
 },
 typeByDefValue: (bool) false,
 onConfigChange: (func(fsnotify.Event)) <nil>
})
```

As evident from the output, a call to `viper.Sub("foo.array")`  returns `(*viper.Viper)(<nil>)`.

On a side note, the code was panicking earlier, but I am unable to reproduce it now. 

```
GET foo.name
(string) (len=3) "foo"
GET foo.array
([]interface {}) (len=2 cap=2) {
 (string) (len=3) "bar",
 (string) (len=3) "baz"
}
GET foo.dict
(interface {}) <nil>
SUB foo.dict
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x46f262]

goroutine 1 [running]:
github.com/spf13/viper.(*Viper).Sub(0xc8200aa380, 0x720020, 0x8, 0xc82003e010)
    /home/satyenr/go/src/github.com/spf13/viper/viper.go:529 +0x372
github.com/spf13/viper.Sub(0x720020, 0x8, 0x1)
    /home/satyenr/go/src/github.com/spf13/viper/viper.go:525 +0x37
main.main()
    /home/satyenr/go/src/test/viper-test.go:58 +0xee1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
exit status 2

```

**Comment by tcheard** [comment]
This is because viper.Sub requires the value to be a map otherwise it returns nil.

https://github.com/spf13/viper/blob/master/viper.go#L660

And if the value is a slice, it will return nil.

As such this is related to #91

**Comment by marcofranssen** [comment]
I can confirm it also doesn't work with a Map.

```go
logger.Debug("Configuration", zap.Any("config", viper.AllSettings()))
logger.Debug("Configuration", zap.Any("serverConfig", viper.Sub("server")))
```

```bash
2020-01-15T15:53:24.724+0100    DEBUG   cmd/root.go:37  Configuration   {"config": {"remote_server":{"url":"https://notary.docker.io"},"server":{"listen_addr":":8086","listen_addr_tls":":8443"},"trust_dir":"~/.docker/trust"}}
2020-01-15T15:53:24.724+0100    DEBUG   cmd/root.go:38  Configuration   {"serverConfig": {}}
```

As seen in the first log line `server` is a Map with 2 keys.
As seen in the second log line `server` is `nil` when using with sub.

**Comment by andig** [comment]
#509 should provide a solution using `SubList`
