### ISSUE TITLE
Calling OnConfigChange() is mandatory, contradicting the README

### ISSUE THREAD

**Issue by yberreby** [spf13/viper#175]
A program using `WatchConfig()` **crashes** on config change if the `viper.onConfigChange` field is nil
(not set) - that is, **if `viper.OnConfigChange()` was not called**.

This contradicts the README, which states it is **not** required to call this function: 

> Viper supports the ability to have your application live read a config file while running.
> 
> Gone are the days of needing to restart a server to have a config take effect, viper powered applications can read an update to a config file while running and not miss a beat.
> 
> Simply tell the viper instance to watchConfig. Optionally you can provide a function for Viper to run each time a change occurs.
> 
> **Optionally** you can provide a function for Viper to run each time a change occurs.

Test program:

``` go
package main

import "github.com/spf13/viper"
import "fmt"
import "time"

func main() {
    viper.SetConfigName("config")
    viper.AddConfigPath(".")
    viper.SetConfigType("toml")
    err := viper.ReadInConfig()
    if err != nil {
        panic(fmt.Errorf("Fatal error config file: %s \n", err))
    }

    viper.WatchConfig()

    // If config.toml is edited while main() is sleeping, the program
    // crashes.

    // Uncommenting these three lines fixes the problem

    //viper.OnConfigChange(func(e fsnotify.Event) {
    //  fmt.Println("Config file changed:", e.Name)
    //})

    time.Sleep(8 * time.Second)

    fmt.Printf("key = %s", viper.GetString("key"))
}
```

```
❯ ./main
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x69701]

goroutine 4 [running]:
panic(0x2b0d00, 0xc82000a100)
    /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/spf13/viper.(*Viper).WatchConfig.func1.1(0xc820108120, 0xc820086af0, 0x45, 0xc8201000e0)
    /Users/yberreby/code/go/src/github.com/spf13/viper/viper.go:256 +0x351
created by github.com/spf13/viper.(*Viper).WatchConfig.func1
    /Users/yberreby/code/go/src/github.com/spf13/viper/viper.go:263 +0x203
```

To reproduce the bug, **save `config.toml`** while the test program is sleeping.

**Comment by toudi** [comment]
hi. I have also encountered this issue, however what helped in my case was to move the `viper.OnConfigChange()` call *before* `viper.WatchConfig()`, like so:

```
	viper.OnConfigChange(func(e fsnotify.Event) {
		fmt.Println("Config file changed")
	})

	viper.WatchConfig()
```

when I had it the other way around (like it's suggested in the above comment, and the Readme) I was still having `panic()` - which is kind of understood, given that you first have to initiate the handler, only then can you actually use it.

This is in reverse order from what is in the Readme file, however I'm still so new to go I may mis-interpret things .. :)

**Comment by defond0** [comment]
I believe that this issue is now solved https://github.com/spf13/viper/commit/e0f7631cf3ac7e7530949c7e154855076b0a4c17 has a nil check on the OnConfigChange and this issue may be closed.
