### ISSUE TITLE
Segfault When binding to nil PFlag

### ISSUE THREAD

**Issue by Toasterson** [spf13/viper#422]
Hello 

The Latest version of viper segfaults when binding with pflags.

Edit:
Turns out I am a moron and this does not happen with the code all the time but when you try to bind to a flag that does not exist.

Say you have
```go
RootCmd.PersistentFlags().String("loglevel", "", "Set the Log Level")
viper.BindPFlag("loglevel", RootCmd.Flags().Lookup("loglevel"))
```
This Will cause the Segfault below.

Cerrectly you would need
```go
RootCmd.PersistentFlags().String("loglevel", "", "Set the Log Level")
viper.BindPFlag("loglevel", RootCmd.PersistentFlags().Lookup("loglevel"))
```
Notice the PersistenFlags in both lines.

This is not easy to debug when you are totaly blind like I am.
Can we have an error Message that tells that the pointer to PFlag is nil and one should revisit the code?

Tested with Go 1.9 and 1.8.3 on Linux and Solaris. Same result both times.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x822ed5]

goroutine 1 [running]:
github.com/spf13/viper.pflagValue.HasChanged(0x0, 0xc4200df5c0)
	/export/home/toast/workspace/src/github.com/spf13/viper/flags.go:41 +0x5
github.com/spf13/viper.(*Viper).find(0xc4200fc2d0, 0xb75128, 0x8, 0x8, 0xc420160039)
	/export/home/toast/workspace/src/github.com/spf13/viper/viper.go:893 +0xf17
github.com/spf13/viper.(*Viper).Get(0xc4200fc2d0, 0xb75128, 0x8, 0xb71996, 0x5)
	/export/home/toast/workspace/src/github.com/spf13/viper/viper.go:594 +0x7c
github.com/spf13/viper.(*Viper).GetString(0xc4200fc2d0, 0xb75128, 0x8, 0xc4201620a0, 0x0)
	/export/home/toast/workspace/src/github.com/spf13/viper/viper.go:649 +0x3f
github.com/spf13/viper.GetString(0xb75128, 0x8, 0xc4201600f0, 0xc42016e0f0)
	/export/home/toast/workspace/src/github.com/spf13/viper/viper.go:647 +0x41
git.wegmueller.it/opencloud/opencloud/cmd/imageadm/cmd.preRun(0xeca600, 0xc420170120, 0x2, 0x3)
	/export/home/toast/workspace/src/git.wegmueller.it/opencloud/opencloud/cmd/imageadm/cmd/root.go:36 +0x48
github.com/spf13/cobra.(*Command).execute(0xeca600, 0xc420170090, 0x3, 0x3, 0xeca600, 0xc420170090)
	/export/home/toast/workspace/src/github.com/spf13/cobra/command.go:726 +0x5af
github.com/spf13/cobra.(*Command).ExecuteC(0xecaa80, 0x1, 0x0, 0x0)
	/export/home/toast/workspace/src/github.com/spf13/cobra/command.go:827 +0x349
github.com/spf13/cobra.(*Command).Execute(0xecaa80, 0xc420000340, 0xc4200d5f78)
	/export/home/toast/workspace/src/github.com/spf13/cobra/command.go:780 +0x2b
git.wegmueller.it/opencloud/opencloud/cmd/imageadm/cmd.Execute()
	/export/home/toast/workspace/src/git.wegmueller.it/opencloud/opencloud/cmd/imageadm/cmd/root.go:29 +0x3f
main.main()
	/export/home/toast/workspace/src/git.wegmueller.it/opencloud/opencloud/cmd/imageadm/imageadm.go:20 +0x20
```

**Comment by Toasterson** [comment]
Updated with cause after finding out it was an error on my part and viper actually works in this release.

Can we have an error Message that tells that the pointer to PFlag is nil and one should revisit the code?

**Comment by hanlins** [comment]
Have this issue and currently what I do is use `BindPFlags` instead of manually enter keys. Hope that helps.

**Comment by sagikazarmark** [comment]
Viper checks for nil flags now: https://github.com/spf13/viper/blob/c43197d858bd35c780348a48875e81af29999b1b/viper.go#L1099
