### ISSUE TITLE
win10 panic when file change

### ISSUE THREAD

**Issue by kingeasternsun** [spf13/viper#457]
```go
func viperWatchMain() {

	//设置配置文件的名称
	viper.SetConfigName("viperj") // name of config file (without extension)

	//设置配置文件的可能的多个路径
	viper.AddConfigPath("./doc/")   // path to look for the config file in
	viper.AddConfigPath("$HOME/.appname")  // call multiple times to add many search paths
	viper.AddConfigPath(".")               // optionally look for config in the working directory

	//设置配置文件的路径
	viper.SetDefault("ContentDir", "default")
	
	err := viper.ReadInConfig() // Find and read the config file
	if err != nil { // Handle errors reading the config file
		panic(fmt.Errorf("Fatal error config file: %s \n", err))
	}

	fmt.Println(viper.GetString("ContentDir")) //如果viper.toml文件中 配置了ContentDir，则返回实际配置的值，如果没有配置，则返回配置的默认值

	viper.WatchConfig()
	viper.OnConfigChange(func(e fsnotify.Event) {
		fmt.Println("Config file changed:")
	})

	for {

	}
}

```

when i mofify the file viperj.json, then i got 
```
PS F:\ubuntushare\gitlab\tool> go run .\main.go .\vipercfg.go
ContentDir json2
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x768a79]

goroutine 5 [running]:
github.com/spf13/viper.(*Viper).WatchConfig.func1.1(0xc042032080, 0xc042068300, 0x2a, 0xc0420860f0)
        F:/gitlab/src/github.com/spf13/viper/viper.go:292 +0x339
created by github.com/spf13/viper.(*Viper).WatchConfig.func1
        F:/gitlab/src/github.com/spf13/viper/viper.go:281 +0x225
exit status 2
```

**Comment by Demitroi** [comment]
I have the same problem with Windows 7 X64

**Comment by MichaelHipp** [comment]
I also have this issue running on Ubuntu 18.04.

**Comment by hemancuso** [comment]
Replicated on go1.10 darwin/amd64

**Comment by asahasrabuddhe** [comment]
Replicated on go version go1.10.3 linux/amd64

@spf13 Any comments or solution here?

**Comment by mcauto** [comment]
Replicated on go version go1.11.2 linux/amd64

**Comment by mcauto** [comment]
In my case, [os.Getenv](https://github.com/spf13/viper/blob/master/util.go#L100) is not working environment.


```bash
export CONFIG_PATH = /tmp
```

```go
func TestGetenv(t *testing.T){
        path := os.Getenv("CONFIG_PATH")
        fmt.Println(path)
}
```
