### ISSUE TITLE
viper panics when binding a  persistent flag with a different name

### ISSUE THREAD

**Issue by iamneal** [spf13/viper#677]
I have two commands that want to use the same flag names, [that isn't possible]() so I decided to have viper bind the flags with a prefixed value

```go
func init() {
	rootCmd.AddCommand(readCmd)

	readCmd.Flags().StringP("input", "i", "", ".proto file to read queries from")
	readCmd.Flags().StringP("output", "o", "", ".pete file to write queries to")
	readCmd.Flags().StringSliceP("names", "n", nil, "names of the queries to read")
	readCmd.Flags().BoolP("all", "a", false, "read all the queries")

	//prefixed because of https://github.com/spf13/viper/issues/567
	viper.BindPFlag("read-input", readCmd.Flags().Lookup("input"))
	viper.BindPFlag("read-output", readCmd.Flags().Lookup("output"))
	viper.BindPFlag("read-names", readCmd.Flags().Lookup("names"))
	viper.BindPFlag("read-prefix", readCmd.Flags().Lookup("prefix"))
	viper.BindPFlag("read-all", readCmd.Flags().Lookup("all"))
	viper.BindPFlag("read-deli", readCmd.PersistentFlags().Lookup("deli"))
}
```
"deli" is a persistent flag set on the root with a default value.

if I run my command without setting a value:
`$ pete read -n=GetCatByName -i=./test/pets.proto --output=./test/pet_queries.pete`

I get a panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x13b3b75]

goroutine 1 [running]:
github.com/spf13/viper.pflagValue.HasChanged(0x0, 0x23)
        /Users/nealcooper/go/src/github.com/spf13/viper/flags.go:41 +0x5
github.com/spf13/viper.(*Viper).find(0xc0000ce200, 0x14a0ea3, 0x9, 0x9, 0x17)
        /Users/nealcooper/go/src/github.com/spf13/viper/viper.go:985 +0xe5c
github.com/spf13/viper.(*Viper).Get(0xc0000ce200, 0x14a0ea3, 0x9, 0x17, 0xc0000fa4b0)
        /Users/nealcooper/go/src/github.com/spf13/viper/viper.go:669 +0x7c
github.com/spf13/viper.(*Viper).GetString(0xc0000ce200, 0x14a0ea3, 0x9, 0x7ffeefbff8d8, 0x17)
        /Users/nealcooper/go/src/github.com/spf13/viper/viper.go:726 +0x3f
github.com/spf13/viper.GetString(0x14a0ea3, 0x9, 0xc0000fa4b0, 0x46)
        /Users/nealcooper/go/src/github.com/spf13/viper/viper.go:724 +0x41
github.com/iamneal/pete/cmd.glob..func1(0x17fbbe0, 0xc000099830, 0x0, 0x3)
        /Users/nealcooper/go/src/github.com/iamneal/pete/cmd/read.go:47 +0x1ba
github.com/spf13/cobra.(*Command).execute(0x17fbbe0, 0xc0000997a0, 0x3, 0x3, 0x17fbbe0, 0xc0000997a0)
        /Users/nealcooper/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x17fbe40, 0x0, 0x0, 0x0)
        /Users/nealcooper/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x17fbe40, 0x10074e0, 0xc000084058)
        /Users/nealcooper/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/iamneal/pete/cmd.Execute()
        /Users/nealcooper/go/src/github.com/iamneal/pete/cmd/root.go:89 +0x2d
main.main()
```

I added some logging to viper.go.  This flag is reporting that it exists, but it is actually nil for some reason.

```go
// Given a key, find the value.
// Viper will check in the following order:
// flag, env, config file, key/value store, default.
// Viper will check to see if an alias exists first.
// Note: this assumes a lower-cased key given.
func (v *Viper) find(lcaseKey string) interface{} {

	var (
		val    interface{}
		exists bool
		path   = strings.Split(lcaseKey, v.keyDelim)
		nested = len(path) > 1
	)

	// compute the path through the nested maps to the nested value
	if nested && v.isPathShadowedInDeepMap(path, castMapStringToMapInterface(v.aliases)) != "" {
		return nil
	}

	// if the requested key is an alias, then return the proper key
	lcaseKey = v.realKey(lcaseKey)
	path = strings.Split(lcaseKey, v.keyDelim)
	nested = len(path) > 1

	// Set() override first
	val = v.searchMap(v.override, path)
	if val != nil {
		return val
	}
	if nested && v.isPathShadowedInDeepMap(path, v.override) != "" {
		return nil
	}

	// PFlag override next
	flag, exists := v.pflags[lcaseKey]
	fmt.Printf("lcaseKey +%v\n exists +%v\n flag +%v\n", lcaseKey, exists, flag)// <------ added
	if exists && flag.HasChanged() {
		switch flag.ValueType() {
		case "int", "int8", "int16", "int32", "int64":
			return cast.ToInt(flag.ValueString())
		case "bool":
			return cast.ToBool(flag.ValueString())
		case "stringSlice":
			s := strings.TrimPrefix(flag.ValueString(), "[")
			s = strings.TrimSuffix(s, "]")
			res, _ := readAsCSV(s)
			return res
		default:
			return flag.ValueString()
		}
	}
	if nested && v.isPathShadowedInFlatMap(path, v.pflags) != "" {
		return nil
	}

	// Env override next
	if v.automaticEnvApplied {
		// even if it hasn't been registered, if automaticEnv is used,
		// check any Get request
		if val, ok := v.getEnv(v.mergeWithEnvPrefix(lcaseKey)); ok {
			return val
		}
		if nested && v.isPathShadowedInAutoEnv(path) != "" {
			return nil
		}
	}
	envkey, exists := v.env[lcaseKey]
	if exists {
		if val, ok := v.getEnv(envkey); ok {
			return val
		}
	}
	if nested && v.isPathShadowedInFlatMap(path, v.env) != "" {
		return nil
	}

	// Config file next
	val = v.searchMapWithPathPrefixes(v.config, path)
	if val != nil {
		return val
	}
	if nested && v.isPathShadowedInDeepMap(path, v.config) != "" {
		return nil
	}

	// K/V store next
	val = v.searchMap(v.kvstore, path)
	if val != nil {
		return val
	}
	if nested && v.isPathShadowedInDeepMap(path, v.kvstore) != "" {
		return nil
	}

	// Default next
	val = v.searchMap(v.defaults, path)
	if val != nil {
		return val
	}
	if nested && v.isPathShadowedInDeepMap(path, v.defaults) != "" {
		return nil
	}

	// last chance: if no other value is returned and a flag does exist for the value,
	// get the flag's value even if the flag's value has not changed
	if flag, exists := v.pflags[lcaseKey]; exists {
		switch flag.ValueType() {
		case "int", "int8", "int16", "int32", "int64":
			return cast.ToInt(flag.ValueString())
		case "bool":
			return cast.ToBool(flag.ValueString())
		case "stringSlice":
			s := strings.TrimPrefix(flag.ValueString(), "[")
			s = strings.TrimSuffix(s, "]")
			res, _ := readAsCSV(s)
			return res
		default:
			return flag.ValueString()
		}
	}
	// last item, no need to check shadowing

	return nil
}
```
all I did was print the key, what exist reported, and the flag.  When rerunning with the logging
```
$ pete read -n=GetCatByName -i=./test/pets.proto --output=./test/pet_queries.pete
read called
lcaseKey +read-input
 exists +true
 flag +{0xc0000c9400}
lcaseKey +read-output
 exists +true
 flag +{0xc0000c94a0}
lcaseKey +read-deli
 exists +true
 flag +{<nil>}
panic: runtime error: invalid memory address or nil pointer dereference
```

I'm not sure what exactly I'm doing wrong, maybe this pattern is more suitable to be used with multiple vipers?

**Comment by xanuthatusu** [comment]
Context/Background
===============
I was able to take a look at your `pete` repo and debug your issue. I don't think you actually provide enough information in this issue to be able to fully answer it. I will try to provide the missing context.

You have a `deli` flag in your `rootCmd` that you made persistent. Your goal is to have a flag in your `readCmd` called `deli` that has the same configuration. You've tried to create a _new_ persistent flag called `deli` in your `readCmd`

Solution
-----------------

From my understanding, this is breaking because of your use of `PersistentFlags`. You should define a persistent flag in your `rootCmd` 
`rootCmd.PersistentFlags().StringP("deli", "d", "\n\n", "the delimiter to use")`
and then bind it to your viper instance
`viper.BindPFlag("deli", rootCmd.PersistentFlags().Lookup("deli"))`

You will have access to `viper.GetString("deli")` even in your `readCmd` because the flag is persistent. Your default value for `deli` will also be used.

`pete -d=","` -> `viper.GetString("deli") == ","`
`pete read -d=","` -> `viper.GetString("deli") == ","`

Explanation
--------------------

You were getting an error where `read-deli` was being set to `<nil>` because when you try to bind it to your viper by
`viper.BindPFlag("read-deli", readCmd.PersistentFlags().Lookup("deli"))`

But `readCmd` doesn't have a persistent flag named `deli`. I saw that you tried to fix this by trying to add
`readCmd.PersistentFlags().StringP("deli", "d", "\n\n", "the delimiter to use")`

But now there's a conflict with flags, because the `rootCmd` provides the `deli` to any of the sub-commands because it's persistent. If you really wanted `viper.GetString("read-deli")` to work, you could add
`viper.BindPFlag("read-deli", rootCmd.PersistentFlags().Lookup("deli"))`
but
`viper.GetString("read-deli")` would be equivalent to `viper.GetString("deli")`

otherwise, you can just remove any declaration or bindings of the `deli` flag in your `readCmd` and call `viper.GetString("deli")` and it should work how you expected.
