### ISSUE TITLE
call to `viper.AllSettings()` panics (race condition?)

### ISSUE THREAD

**Issue by pswenson** [spf13/viper#695]
I am getting a panic when I call `viper.AllSettings()`.  v1.3.2

Looks like a race condition, I assume app is modifying the underlying config while config is being iterated... note I'm a go novice so perhaps there is an easy way to deal with it....

but perhaps either there should be doc or a feature to read in a config while it may be modified?

full trace:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x4442f05]

goroutine 1 [running]:
github.myco.com/yggdrasil/go/exit.Handle()
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/exit/exit.go:41 +0xa1
panic(0x48af920, 0x515db30)
	/usr/local/Cellar/go/1.12.3/libexec/src/runtime/panic.go:522 +0x1b5
github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper.pflagValue.HasChanged(0x0, 0xc0000e33b0)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper/flags.go:41 +0x5
github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper.(*Viper).find(0xc0000ec200, 0x4992435, 0xb, 0xb, 0x4014d84)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper/viper.go:978 +0x11bb
github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper.(*Viper).Get(0xc0000ec200, 0x4992435, 0xb, 0xc, 0xc0002ec638)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper/viper.go:669 +0x7c
github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper.(*Viper).AllSettings(0xc0000ec200, 0x4994ab6)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper/viper.go:1728 +0xb7
github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper.AllSettings(...)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/vendor/github.com/spf13/viper/viper.go:1723
github.myco.com/yggdrasil/go/fourier/cmd.glob..func33(0x516b180, 0xc000172e70, 0x0, 0x1)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/fourier/cmd/root.go:79 +0x151
github.myco.com/yggdrasil/go/vendor/github.com/spf13/cobra.(*Command).execute(0x516b180, 0xc0000d4010, 0x1, 0x1, 0x516b180, 0xc0000d4010)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/vendor/github.com/spf13/cobra/command.go:755 +0x4e2
github.myco.com/yggdrasil/go/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x516b180, 0x49d33d0, 0x47da7ce, 0x516b180)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.myco.com/yggdrasil/go/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/vendor/github.com/spf13/cobra/command.go:800
github.myco.com/yggdrasil/go/fourier/cmd.Execute()
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/fourier/cmd/root.go:228 +0x72
main.main()
	/Users/pswens200/dev/gowork/src/github.myco.com/yggdrasil/go/fourier/main.go:7 +0x20
```

**Comment by LandonTClipp** [comment]
When will this be merged into upstream? This is posing a big problem for my project.

**Comment by okwme** [comment]
bump

**Comment by drewwells** [comment]
Is `AllSettings()` callable? I get a panic anywhere I put it in the execution.
