### ISSUE TITLE
ReadInConfig could not find the path

### ISSUE THREAD

**Issue by xichengliudui** [spf13/viper#853]
go.mod
```
github.com/spf13/cast v1.3.1
github.com/spf13/cobra v0.0.5
github.com/spf13/viper v1.4.0
```

```go
func init() {
	startCmd.PersistentFlags().StringVarP(&bootstrap.Args.ConfigFile, "config", "c", "config/in-local.toml",
		"Start server with provided configuration file")

	rootCmd.AddCommand(startCmd)
	rootCmd.AddCommand(version.Command())
}
func start(_ *cobra.Command, _ []string) error {
	parseConfig()
}
func parseConfig() {
	viper.SetConfigFile(bootstrap.Args.ConfigFile)
	log.Info("bootstrap.Args.ConfigFile is %s", bootstrap.Args.ConfigFile)
	err := viper.ReadInConfig()
	if err != nil {
		panic(fmt.Errorf("parse config file fail: %s", err))
	}
}
```
```
$ ./beyondmesh start
APP]> (1892) 2020-02-25 17:26:28 [INFO]  bootstrap.Args.ConfigFile is config/in-local.toml
panic: parse config file fail: open config/in-local.toml: The system cannot find the path specified.

goroutine 1 [running]:
main.parseConfig()
        C:/Users/edz/go/src/BeyondMesh/src/api/main.go:122 +0x1b9
main.start(0x344d260, 0x348e208, 0x0, 0x0, 0x0, 0x0)
        C:/Users/edz/go/src/BeyondMesh/src/api/main.go:71 +0x3b
github.com/spf13/cobra.(*Command).execute(0x344d260, 0x348e208, 0x0, 0x0, 0x344d260, 0x348e208)
```

**Comment by xichengliudui** [comment]
my directory structure is：
```
config ->  in-local.toml
src    ->  api  ->  main.go
......
```
