### ISSUE TITLE
viper.SetEnvKeyReplacer(nil) results in Segmentation Fault upon subsequent viper.Get()

### ISSUE THREAD

**Issue by markwort** [spf13/viper#960]
In my application, I need to sometimes check the settings that viper returns without applying any replacements to the environment keys.
For that, I have tried:
```
viper.SetEnvKeyReplacer(nil)
```
But the subsequent call to `viper.Get()` will result in a Segmentation Fault...
If I instead do
```
viper.SetEnvKeyReplacer(strings.NewReplacer("",""))
```
It works as expected.

I'm really curious why we'd get a Segmentation Fault, it looks like the code is explicitly veryfying that the Replacer is not nil: https://github.com/spf13/viper/blob/3826be313591f83193f048520482a7b3cf17d506/viper.go#L452-L454

I'm on go 1.14, viper is at current master, more details at the end...

Here's a "minimal reproducer":
```bash
[user@host tmp]$ cat test.go
package main

import (
	"fmt"
	"github.com/spf13/viper"
	"strings"
)

func main() {

	viper.SetEnvPrefix("test")
	viper.AutomaticEnv()
	//replace dashes (in flags) with underscores (in ENV vars)
	viper.SetEnvKeyReplacer(strings.NewReplacer("-", "_"))

	fmt.Println(viper.Get("key-dash"))
	viper.SetEnvKeyReplacer(strings.NewReplacer("", ""))
	fmt.Println(viper.Get("key-dash"))
	viper.SetEnvKeyReplacer(nil)
	fmt.Println(viper.Get("key-dash"))
}
[user@host tmp]$ go build test.go
[user@host tmp]$ TEST_KEY_DASH=dadadadada ./test
dadadadada
<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4e7496]

goroutine 1 [running]:
strings.(*Replacer).Replace(0x0, 0xc000026a50, 0xd, 0xc000026a40, 0xd)
	/usr/lib/go/src/strings/replace.go:96 +0x26
github.com/spf13/viper.(*Viper).getEnv(0xc0000be900, 0xc000026a50, 0xd, 0xc000026a50, 0xd, 0x0)
	/home/user/go/src/github.com/spf13/viper/viper.go:453 +0xb7
github.com/spf13/viper.(*Viper).find(0xc0000be900, 0x8dd094, 0x8, 0x1, 0x4d7fb7, 0xc0000a3450)
	/home/user/go/src/github.com/spf13/viper/viper.go:1082 +0xd50
github.com/spf13/viper.(*Viper).Get(0xc0000be900, 0x8dd094, 0x8, 0x1, 0x1)
	/home/user/go/src/github.com/spf13/viper/viper.go:728 +0x81
github.com/spf13/viper.Get(...)
	/home/user/go/src/github.com/spf13/viper/viper.go:725
main.main()
	/tmp/test.go:20 +0x3e5
[user@host tmp]$ go version
go version go1.14.5 linux/amd64
[user@host tmp]$ cd /home/user/go/src/github.com/spf13/viper/
[user@host viper]$ git log --oneline | head -n 5
3826be3 Simplify $HOME prefix check
ce53404 Fix environment variable expansion in absPathify
13494e8 Skipping error != nil checks in favor of the fast return.
13df721 Add Go 1.14 to build targets
3856c05 Fix: Getting the value of a StringToString pflag (#874)
```

**Comment by sagikazarmark** [comment]
`SetEnvKeyReplacer` accepts a `*strings.Replacer`: https://github.com/spf13/viper/blob/master/viper.go#L1419

Try this instead: `viper.SetEnvKeyReplacer(strings.NewReplacer())`

On a separate note: changing Viper's internal behavior is not going to be allowed in v2. You will be able to set this on initialization, but not change it later.
